server:
  port: 83
spring:
  application:
    name: cloud-nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


service-url:
  nacos-use-service: http://cloud-nacos-payment-provider #payment支付提供者的service name