server:
  port: 8002
  servlet:
    session:
      timeout: 3000m
      persistent: true
    context-path: /api

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 2000MB
  thymeleaf:
    enabled: true
    prefix: classpath:/static/
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gxl.study.springcloud.entity
logging:
  level:
    com.gxl.study.cloud.payment.mapper: debug


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/ #单机
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: payment8002
    prefer-ip-address: true