server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server7002

eureka:
  instance:
    hostname: eureka7002
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护模式，保证不可用服务被及时删除
    enable-self-preservation: false
    #清理无效节点时间间隔 默认60s, 单位ms
    eviction-interval-timer-in-ms: 2000